//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CheeseWorldTestModel", "FK_tblProduct_tblCheese", "tblCheese", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CheeseWorldPOS.tblCheese), "tblProduct", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CheeseWorldPOS.tblProduct), true)]
[assembly: EdmRelationshipAttribute("CheeseWorldTestModel", "FK_tblProduct_tblMeat", "tblMeat", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CheeseWorldPOS.tblMeat), "tblProduct", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CheeseWorldPOS.tblProduct), true)]
[assembly: EdmRelationshipAttribute("CheeseWorldTestModel", "FK_tblProduct_tblMisc", "tblMisc", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CheeseWorldPOS.tblMisc), "tblProduct", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CheeseWorldPOS.tblProduct), true)]
[assembly: EdmRelationshipAttribute("CheeseWorldTestModel", "FK_tblTransactionItem_tblProduct", "tblProduct", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CheeseWorldPOS.tblProduct), "tblTransactionItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CheeseWorldPOS.tblTransactionItem), true)]
[assembly: EdmRelationshipAttribute("CheeseWorldTestModel", "FK_tblTransactionItem_tblTransaction", "tblTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CheeseWorldPOS.tblTransaction), "tblTransactionItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CheeseWorldPOS.tblTransactionItem), true)]

#endregion

namespace CheeseWorldPOS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CheeseWorldTestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CheeseWorldTestEntities object using the connection string found in the 'CheeseWorldTestEntities' section of the application configuration file.
        /// </summary>
        public CheeseWorldTestEntities() : base("name=CheeseWorldTestEntities", "CheeseWorldTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CheeseWorldTestEntities object.
        /// </summary>
        public CheeseWorldTestEntities(string connectionString) : base(connectionString, "CheeseWorldTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CheeseWorldTestEntities object.
        /// </summary>
        public CheeseWorldTestEntities(EntityConnection connection) : base(connection, "CheeseWorldTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCheese> tblCheese
        {
            get
            {
                if ((_tblCheese == null))
                {
                    _tblCheese = base.CreateObjectSet<tblCheese>("tblCheese");
                }
                return _tblCheese;
            }
        }
        private ObjectSet<tblCheese> _tblCheese;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMeat> tblMeats
        {
            get
            {
                if ((_tblMeats == null))
                {
                    _tblMeats = base.CreateObjectSet<tblMeat>("tblMeats");
                }
                return _tblMeats;
            }
        }
        private ObjectSet<tblMeat> _tblMeats;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMisc> tblMiscs
        {
            get
            {
                if ((_tblMiscs == null))
                {
                    _tblMiscs = base.CreateObjectSet<tblMisc>("tblMiscs");
                }
                return _tblMiscs;
            }
        }
        private ObjectSet<tblMisc> _tblMiscs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblProduct> tblProducts
        {
            get
            {
                if ((_tblProducts == null))
                {
                    _tblProducts = base.CreateObjectSet<tblProduct>("tblProducts");
                }
                return _tblProducts;
            }
        }
        private ObjectSet<tblProduct> _tblProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTransaction> tblTransactions
        {
            get
            {
                if ((_tblTransactions == null))
                {
                    _tblTransactions = base.CreateObjectSet<tblTransaction>("tblTransactions");
                }
                return _tblTransactions;
            }
        }
        private ObjectSet<tblTransaction> _tblTransactions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTransactionItem> tblTransactionItems
        {
            get
            {
                if ((_tblTransactionItems == null))
                {
                    _tblTransactionItems = base.CreateObjectSet<tblTransactionItem>("tblTransactionItems");
                }
                return _tblTransactionItems;
            }
        }
        private ObjectSet<tblTransactionItem> _tblTransactionItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCheese EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCheese(tblCheese tblCheese)
        {
            base.AddObject("tblCheese", tblCheese);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMeats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMeats(tblMeat tblMeat)
        {
            base.AddObject("tblMeats", tblMeat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMiscs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMiscs(tblMisc tblMisc)
        {
            base.AddObject("tblMiscs", tblMisc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblProducts(tblProduct tblProduct)
        {
            base.AddObject("tblProducts", tblProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTransactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTransactions(tblTransaction tblTransaction)
        {
            base.AddObject("tblTransactions", tblTransaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTransactionItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTransactionItems(tblTransactionItem tblTransactionItem)
        {
            base.AddObject("tblTransactionItems", tblTransactionItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="tblCheese")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCheese : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCheese object.
        /// </summary>
        /// <param name="cheeseID">Initial value of the CheeseID property.</param>
        public static tblCheese CreatetblCheese(global::System.Int32 cheeseID)
        {
            tblCheese tblCheese = new tblCheese();
            tblCheese.CheeseID = cheeseID;
            return tblCheese;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CheeseID
        {
            get
            {
                return _CheeseID;
            }
            set
            {
                if (_CheeseID != value)
                {
                    OnCheeseIDChanging(value);
                    ReportPropertyChanging("CheeseID");
                    _CheeseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CheeseID");
                    OnCheeseIDChanged();
                }
            }
        }
        private global::System.Int32 _CheeseID;
        partial void OnCheeseIDChanging(global::System.Int32 value);
        partial void OnCheeseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CheeseName
        {
            get
            {
                return _CheeseName;
            }
            set
            {
                OnCheeseNameChanging(value);
                ReportPropertyChanging("CheeseName");
                _CheeseName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CheeseName");
                OnCheeseNameChanged();
            }
        }
        private global::System.String _CheeseName;
        partial void OnCheeseNameChanging(global::System.String value);
        partial void OnCheeseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cheeseGroup
        {
            get
            {
                return _cheeseGroup;
            }
            set
            {
                OncheeseGroupChanging(value);
                ReportPropertyChanging("cheeseGroup");
                _cheeseGroup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cheeseGroup");
                OncheeseGroupChanged();
            }
        }
        private Nullable<global::System.Int32> _cheeseGroup;
        partial void OncheeseGroupChanging(Nullable<global::System.Int32> value);
        partial void OncheeseGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cheeseQunatity
        {
            get
            {
                return _cheeseQunatity;
            }
            set
            {
                OncheeseQunatityChanging(value);
                ReportPropertyChanging("cheeseQunatity");
                _cheeseQunatity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cheeseQunatity");
                OncheeseQunatityChanged();
            }
        }
        private Nullable<global::System.Decimal> _cheeseQunatity;
        partial void OncheeseQunatityChanging(Nullable<global::System.Decimal> value);
        partial void OncheeseQunatityChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblProduct_tblCheese", "tblProduct")]
        public EntityCollection<tblProduct> tblProducts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblProduct>("CheeseWorldTestModel.FK_tblProduct_tblCheese", "tblProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblProduct>("CheeseWorldTestModel.FK_tblProduct_tblCheese", "tblProduct", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="tblMeat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMeat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMeat object.
        /// </summary>
        /// <param name="meatID">Initial value of the MeatID property.</param>
        public static tblMeat CreatetblMeat(global::System.Int32 meatID)
        {
            tblMeat tblMeat = new tblMeat();
            tblMeat.MeatID = meatID;
            return tblMeat;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeatID
        {
            get
            {
                return _MeatID;
            }
            set
            {
                if (_MeatID != value)
                {
                    OnMeatIDChanging(value);
                    ReportPropertyChanging("MeatID");
                    _MeatID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MeatID");
                    OnMeatIDChanged();
                }
            }
        }
        private global::System.Int32 _MeatID;
        partial void OnMeatIDChanging(global::System.Int32 value);
        partial void OnMeatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MeatName
        {
            get
            {
                return _MeatName;
            }
            set
            {
                OnMeatNameChanging(value);
                ReportPropertyChanging("MeatName");
                _MeatName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MeatName");
                OnMeatNameChanged();
            }
        }
        private global::System.String _MeatName;
        partial void OnMeatNameChanging(global::System.String value);
        partial void OnMeatNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblProduct_tblMeat", "tblProduct")]
        public EntityCollection<tblProduct> tblProducts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblProduct>("CheeseWorldTestModel.FK_tblProduct_tblMeat", "tblProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblProduct>("CheeseWorldTestModel.FK_tblProduct_tblMeat", "tblProduct", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="tblMisc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMisc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMisc object.
        /// </summary>
        /// <param name="miscID">Initial value of the MiscID property.</param>
        public static tblMisc CreatetblMisc(global::System.Int32 miscID)
        {
            tblMisc tblMisc = new tblMisc();
            tblMisc.MiscID = miscID;
            return tblMisc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiscProd
        {
            get
            {
                return _MiscProd;
            }
            set
            {
                OnMiscProdChanging(value);
                ReportPropertyChanging("MiscProd");
                _MiscProd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiscProd");
                OnMiscProdChanged();
            }
        }
        private global::System.String _MiscProd;
        partial void OnMiscProdChanging(global::System.String value);
        partial void OnMiscProdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MiscID
        {
            get
            {
                return _MiscID;
            }
            set
            {
                if (_MiscID != value)
                {
                    OnMiscIDChanging(value);
                    ReportPropertyChanging("MiscID");
                    _MiscID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MiscID");
                    OnMiscIDChanged();
                }
            }
        }
        private global::System.Int32 _MiscID;
        partial void OnMiscIDChanging(global::System.Int32 value);
        partial void OnMiscIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblProduct_tblMisc", "tblProduct")]
        public EntityCollection<tblProduct> tblProducts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblProduct>("CheeseWorldTestModel.FK_tblProduct_tblMisc", "tblProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblProduct>("CheeseWorldTestModel.FK_tblProduct_tblMisc", "tblProduct", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="tblProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblProduct object.
        /// </summary>
        /// <param name="poductID">Initial value of the PoductID property.</param>
        public static tblProduct CreatetblProduct(global::System.Int32 poductID)
        {
            tblProduct tblProduct = new tblProduct();
            tblProduct.PoductID = poductID;
            return tblProduct;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PoductID
        {
            get
            {
                return _PoductID;
            }
            set
            {
                if (_PoductID != value)
                {
                    OnPoductIDChanging(value);
                    ReportPropertyChanging("PoductID");
                    _PoductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PoductID");
                    OnPoductIDChanged();
                }
            }
        }
        private global::System.Int32 _PoductID;
        partial void OnPoductIDChanging(global::System.Int32 value);
        partial void OnPoductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductType
        {
            get
            {
                return _ProductType;
            }
            set
            {
                OnProductTypeChanging(value);
                ReportPropertyChanging("ProductType");
                _ProductType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductType");
                OnProductTypeChanged();
            }
        }
        private global::System.String _ProductType;
        partial void OnProductTypeChanging(global::System.String value);
        partial void OnProductTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MeatID
        {
            get
            {
                return _MeatID;
            }
            set
            {
                OnMeatIDChanging(value);
                ReportPropertyChanging("MeatID");
                _MeatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MeatID");
                OnMeatIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MeatID;
        partial void OnMeatIDChanging(Nullable<global::System.Int32> value);
        partial void OnMeatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CheeseID
        {
            get
            {
                return _CheeseID;
            }
            set
            {
                OnCheeseIDChanging(value);
                ReportPropertyChanging("CheeseID");
                _CheeseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CheeseID");
                OnCheeseIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CheeseID;
        partial void OnCheeseIDChanging(Nullable<global::System.Int32> value);
        partial void OnCheeseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MiscID
        {
            get
            {
                return _MiscID;
            }
            set
            {
                OnMiscIDChanging(value);
                ReportPropertyChanging("MiscID");
                _MiscID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MiscID");
                OnMiscIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MiscID;
        partial void OnMiscIDChanging(Nullable<global::System.Int32> value);
        partial void OnMiscIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblProduct_tblCheese", "tblCheese")]
        public tblCheese tblCheese
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCheese>("CheeseWorldTestModel.FK_tblProduct_tblCheese", "tblCheese").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCheese>("CheeseWorldTestModel.FK_tblProduct_tblCheese", "tblCheese").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCheese> tblCheeseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCheese>("CheeseWorldTestModel.FK_tblProduct_tblCheese", "tblCheese");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCheese>("CheeseWorldTestModel.FK_tblProduct_tblCheese", "tblCheese", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblProduct_tblMeat", "tblMeat")]
        public tblMeat tblMeat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMeat>("CheeseWorldTestModel.FK_tblProduct_tblMeat", "tblMeat").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMeat>("CheeseWorldTestModel.FK_tblProduct_tblMeat", "tblMeat").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMeat> tblMeatReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMeat>("CheeseWorldTestModel.FK_tblProduct_tblMeat", "tblMeat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMeat>("CheeseWorldTestModel.FK_tblProduct_tblMeat", "tblMeat", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblProduct_tblMisc", "tblMisc")]
        public tblMisc tblMisc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMisc>("CheeseWorldTestModel.FK_tblProduct_tblMisc", "tblMisc").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMisc>("CheeseWorldTestModel.FK_tblProduct_tblMisc", "tblMisc").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMisc> tblMiscReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMisc>("CheeseWorldTestModel.FK_tblProduct_tblMisc", "tblMisc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMisc>("CheeseWorldTestModel.FK_tblProduct_tblMisc", "tblMisc", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblTransactionItem_tblProduct", "tblTransactionItem")]
        public EntityCollection<tblTransactionItem> tblTransactionItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTransactionItem>("CheeseWorldTestModel.FK_tblTransactionItem_tblProduct", "tblTransactionItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTransactionItem>("CheeseWorldTestModel.FK_tblTransactionItem_tblProduct", "tblTransactionItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="tblTransaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTransaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTransaction object.
        /// </summary>
        /// <param name="transactionID">Initial value of the TransactionID property.</param>
        public static tblTransaction CreatetblTransaction(global::System.Int32 transactionID)
        {
            tblTransaction tblTransaction = new tblTransaction();
            tblTransaction.TransactionID = transactionID;
            return tblTransaction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                if (_TransactionID != value)
                {
                    OnTransactionIDChanging(value);
                    ReportPropertyChanging("TransactionID");
                    _TransactionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransactionID");
                    OnTransactionIDChanged();
                }
            }
        }
        private global::System.Int32 _TransactionID;
        partial void OnTransactionIDChanging(global::System.Int32 value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TransactionDate
        {
            get
            {
                return _TransactionDate;
            }
            set
            {
                OnTransactionDateChanging(value);
                ReportPropertyChanging("TransactionDate");
                _TransactionDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransactionDate");
                OnTransactionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TransactionDate;
        partial void OnTransactionDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTransactionDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblTransactionItem_tblTransaction", "tblTransactionItem")]
        public EntityCollection<tblTransactionItem> tblTransactionItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblTransactionItem>("CheeseWorldTestModel.FK_tblTransactionItem_tblTransaction", "tblTransactionItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblTransactionItem>("CheeseWorldTestModel.FK_tblTransactionItem_tblTransaction", "tblTransactionItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CheeseWorldTestModel", Name="tblTransactionItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTransactionItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTransactionItem object.
        /// </summary>
        /// <param name="transactionItemID">Initial value of the TransactionItemID property.</param>
        public static tblTransactionItem CreatetblTransactionItem(global::System.Int32 transactionItemID)
        {
            tblTransactionItem tblTransactionItem = new tblTransactionItem();
            tblTransactionItem.TransactionItemID = transactionItemID;
            return tblTransactionItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionItemID
        {
            get
            {
                return _TransactionItemID;
            }
            set
            {
                if (_TransactionItemID != value)
                {
                    OnTransactionItemIDChanging(value);
                    ReportPropertyChanging("TransactionItemID");
                    _TransactionItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransactionItemID");
                    OnTransactionItemIDChanged();
                }
            }
        }
        private global::System.Int32 _TransactionItemID;
        partial void OnTransactionItemIDChanging(global::System.Int32 value);
        partial void OnTransactionItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                OnTransactionIDChanging(value);
                ReportPropertyChanging("TransactionID");
                _TransactionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransactionID");
                OnTransactionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TransactionID;
        partial void OnTransactionIDChanging(Nullable<global::System.Int32> value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductID;
        partial void OnProductIDChanging(Nullable<global::System.Int32> value);
        partial void OnProductIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblTransactionItem_tblProduct", "tblProduct")]
        public tblProduct tblProduct
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProduct>("CheeseWorldTestModel.FK_tblTransactionItem_tblProduct", "tblProduct").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProduct>("CheeseWorldTestModel.FK_tblTransactionItem_tblProduct", "tblProduct").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProduct> tblProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProduct>("CheeseWorldTestModel.FK_tblTransactionItem_tblProduct", "tblProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProduct>("CheeseWorldTestModel.FK_tblTransactionItem_tblProduct", "tblProduct", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CheeseWorldTestModel", "FK_tblTransactionItem_tblTransaction", "tblTransaction")]
        public tblTransaction tblTransaction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTransaction>("CheeseWorldTestModel.FK_tblTransactionItem_tblTransaction", "tblTransaction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTransaction>("CheeseWorldTestModel.FK_tblTransactionItem_tblTransaction", "tblTransaction").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTransaction> tblTransactionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTransaction>("CheeseWorldTestModel.FK_tblTransactionItem_tblTransaction", "tblTransaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTransaction>("CheeseWorldTestModel.FK_tblTransactionItem_tblTransaction", "tblTransaction", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
